<? php
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">';
echo '<script src="https://kit.fontawesome.com/52ac07b561.js" crossorigin="anonymous"></script>';
echo '<title>CURRICULUM VITAE </title>';
echo '<style>';
echo '.top {';
echo 'width: 100%;';
echo 'color: white;';
echo 'background: #303030;';
echo 'padding-top: 15px;';
echo 'padding-bottom: 15px;';
echo '}';
echo '.bottom {';
echo 'width: 100%;';
echo 'background: #303030;';
echo 'padding-top: 10px;';
echo 'padding-bottom: 10px;';
echo '}';
echo '.top-picture {';
echo 'float: right;';
echo 'width: 213px;';
echo 'border: 5px solid white;';
echo 'border-radius: 500px;';
echo '-webkit-border-radius: 500px;';
echo '-moz-border-radius: 500px;';
echo '}';
echo '.top-text {';
echo 'float: left;';
echo 'text-align: center;';
echo '}';
echo '.high-box {';
echo 'padding-top: 10px;';
echo '}';
echo '.low-box {';
echo 'padding-bottom: 10px;';
echo '}';
echo '.line-between-left {';
echo 'padding-left: 30px;';
echo 'border-left: 2px solid #303030;';
echo '}';
echo 'hr.style1{';
echo 'border-top: 3px solid white;';
echo 'width: 75%;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="top"><!--1ra fila-->';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-5">';
echo '<div class="top-picture">';
echo '<img src="https://tinypng.com/web/output/hzcqveqynp3wwybvfwgxnb8b8r3tq0ax/profile.jpg" class="rounded-circle" alt="profile picture">';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-7">';
echo '<div class="top-text">';
echo '<h1><br>Leonardo Daniel</h1>';
echo '<hr class="style1">';
echo '<h2>Ramírez Blanco</h2>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="high-box"><!--2da fila-->';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-5">';
echo '<div>';
echo '<h3><i class="fas fa-user-alt"> Profile</i></h3>';
echo '<p>7th grade student in Computer Engineering at Universidad de Guadalajara</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-7">';
echo '<div class="line-between-left">';
echo '<div>';
echo '<h3><i class="fas fa-briefcase"> Employment</i></h3>';
echo '<ul>';
echo '<li>2018-07/2019-05 Pretroubleshoot B at Jabil</li>';
echo '<li>2017-12/2018-05 Assembler at Sanmina</li>';
echo '<li>2011-03/2017-02 Pretroubleshoot A at Jabil</li>';
echo '</ul>';
echo '<br><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-5">';
echo '<div>';
echo '<h3><i class="fas fa-address-book"> Contact</i></h3>';
echo '<p><i class="fas fa-envelope"></i><a href="http://leonardo.rblanco@alumnos.udg.mx"> leonardo.rblanco</a></p>';
echo '<p><i class="fas fa-phone"></i> 3310688548</p>';
echo '<p><i class="fas fa-home"></i> Tlaquepaque, Jalisco</p>';
echo '<p><i class="fab fa-linkedin"></i><a href="http://linkedin.com/in/leonardo2122"> Leonardo2122</a></p>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-7">';
echo '<div class="line-between-left">';
echo '<div>';
echo '<h3><i class="fas fa-user-graduate"> Education</i></h3>';
echo '<ul>';
echo '<li>7th semester in computer engineering on CUCEI</li>';
echo '<li>Bachlers degree on CENEVAL</li>';
echo '<li>High school certificate on High school No. 20</li>';
echo '</ul>';
echo '<br><br><br><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div><!--3ra fila-->';
echo '</div>';
echo '<div class="container"><!--4ta fila-->';
echo '<div class="row">';
echo '<div class="col-sm-2">';
echo '<div>';
echo '<h3><i class="fas fa-star"> Skills</i></h3>';
echo '<p>Html</p>';
echo '<p>Css</p>';
echo '<p>SQL</p>';
echo '<p>C++</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<br><br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>';
echo '</div>';
echo '<br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>';
echo '</div>';
echo '<br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>';
echo '</div>';
echo '<br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">70%</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-7">';
echo '<div class="line-between-left">';
echo '<div>';
echo '<h3><i class="fas fa-user-tie"> Professional interests</i></h3>';
echo '<ul>';
echo '<li>Database administration</li>';
echo '<li>Equipment support</li>';
echo '</ul>';
echo '</div><br><br><br><br><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container"><!--5ta fila-->';
echo '<div class="row">';
echo '<div class="col-sm-2">';
echo '<div>';
echo '<h3><i class="fas fa-file-excel"> Software</i></h3>';
echo '<p> Excel</p>';
echo '<p> JFLAP</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<br><br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>';
echo '</div>';
echo '<br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">80%</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-7">';
echo '<div class="line-between-left">';
echo '<div>';
echo '<h3><i class="fas fa-project-diagram"> Project Experience</i></h3>';
echo '<ul>';
echo '<li>Basic Sniffer implementation at Computer networks class</li>';
echo '</ul>';
echo '</div>';
echo '<br><br><br><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="low-box"><!--6ta fila-->';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-2">';
echo '<div>';
echo '<h3><i class="fas fa-language"> Languages</i></h3>';
echo '<p>English</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<br><br><br>';
echo '<div class="progress">';
echo '<div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-7">';
echo '<div class="line-between-left">';
echo '<div>';
echo '<h3><i class="fas fa-asterisk"> Personal References</i></h3>';
echo '<ul>';
echo '<li>Saul Ruiz | Developer | 3312463552</li>';
echo '<li>Lizzette Cano | Programer | 3344556633</li>';
echo '</ul><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>
